### ISSUE TITLE
pytorch not compatible with python3.12

### ISSUE THREAD

**Issue by hdillinger** [PTB-MR/mrpro#100]
Add a line suggesting the python version to use in README.
pytorch currently supports Python 3.8-3.11 (https://pytorch.org/get-started/locally/).

**Comment by fzimmermann89** [comment]
We test using python 3.10 and 3.11
With idea plan to support the latest version pytorch supports and the previous one.

So we might drop 3.10 when 3.12 is available for torch (and there is a feature in 3.11 we want to use)

Good idea to add it to the repo readme / change the badge.
