### ISSUE TITLE
2D radial trajectory

### ISSUE THREAD

**Issue by ckolbPTB** [PTB-MR/mrpro#11]
Create 2D (Golden) radial trajectory

Check list:
- [x]     Create branch
- [x]     Implement code
- [ ]     Add comments
- [ ]     Implement tests
- [ ]     Squash commmits
- [ ]     Create PR
- [ ]     Assign reviewer(s) to PR

**Comment by SherineBrahma** [comment]
Hi,

I wrote an initial 2D radial trajectory class (only golden angle now), but it is not refined yet. Is there a way that I can ask someone on Github to review the code without asking for a pull request? @fzimmermann89 @schuenke 

P.S. This is if I do not want to copy and paste my code on Slack.

**Comment by fzimmermann89** [comment]
Perfect!

Just do a pull request.

and mention that you do not want to get this merged right away,  and what you want to have a second opinion on etc.
