### ISSUE TITLE
Hardcoded ignore flags

### ISSUE THREAD

**Issue by ckolbPTB** [PTB-MR/mrpro#119]
Currently we have the ignore flags which define which raw data we do not use for `KData` hardcoded here:
https://github.com/PTB-MR/mrpro/blob/467a3b387a7893289094b6e8d6dd806b869e86f8/src/mrpro/data/_KData.py#L87

The required ignore flags will depend on the type of scan we want to reconstruct so this should be adaptable by the user. 

Suggestion:
```
    def from_file(
        cls,
        filename: str | Path,
        ktrajectory: KTrajectoryCalculator | KTrajectory | KTrajectoryIsmrmrd,
        header_overwrites: dict[str, object] | None = None,
        dataset_idx: int = -1,
        ignore_flags: AcqFlags = AcqFlags.ACQ_IS_NOISE_MEASUREMENT | AcqFlags.ACQ_IS_SURFACECOILCORRECTIONSCAN_DATA
```

**Comment by fzimmermann89** [comment]
I am pretty sure that AcqFlags.ACQ_IS_SURFACECOILCORRECTIONSCAN_DATA is a misnomer.
At least the siemens converter stores `MDH_RAWDATACORRECTION` in this flag, i.e. if the raw data should be corrected by a coilwise factor.

pymapvbvd uses to following to detect non-images:
``` noImaScan = (mask.MDH_ACQEND | mask.MDH_RTFEEDBACK | mask.MDH_HPFEEDBACK
                 | mask.MDH_PHASCOR | mask.MDH_NOISEADJSCAN | mask.MDH_PHASESTABSCAN
                 | mask.MDH_REFPHASESTABSCAN | mask.MDH_SYNCDATA
                 | (mask.MDH_PATREFSCAN & ~mask.MDH_PATREFANDIMASCAN))```
 ```     
       
  with indices into EvalInfoMask as follows:
  ```
   MDH_ACQEND: 0
        MDH_RTFEEDBACK: 1
        MDH_HPFEEDBACK: 2
        MDH_SYNCDATA: 5
        MDH_RAWDATACORRECTION: 10
        MDH_REFPHASESTABSCAN: 14
        MDH_PHASESTABSCAN: 15
        MDH_SIGNREV: 17
        MDH_PHASCOR: 21
        MDH_PATREFSCAN: 22
        MDH_PATREFANDIMASCAN: 23
        MDH_REFLECT: 24
        MDH_NOISEADJSCAN: 25
        MDH_VOP: 53 - 32
```
so        
```
 noImaScan=   0|1|2|21|25|15|14|5
|23&~22
```

which should be
```

(ISMRMRD_ACQ_IS_RTFEEDBACK_DATA)|
(ISMRMRD_ACQ_IS_NAVIGATION_DATA)|
(ISMRMRD_ACQ_IS_HPFEEDBACK_DATA)|
(ISMRMRD_ACQ_IS_PHASECORR_DATA)|
(ISMRMRD_ACQ_IS_NOISE_MEASUREMENT)|
(ISMRMRD_ACQ_IS_PHASE_STABILIZATION)|
(ISMRMRD_ACQ_IS_PHASE_STABILIZATION_REFERENCE)|
(ISMRMRD_ACQ_IS_DUMMYSCAN_DATA)|
(ISMRMRD_ACQ_IS_PARALLEL_CALIBRATION_AND_IMAGING & !ISMRMRD_ACQ_IS_PARALLEL_CALIBRATION)
```

**Comment by fzimmermann89** [comment]
ref:
https://github.com/ismrmrd/siemens_to_ismrmrd/blob/545ee4dfb39db491f4d19e5b843225d08f216ae4/main.cpp#L1225
https://github.com/wtclarke/pymapvbvd/blob/51232649ae4409f1b19f3357158a01938dd79db2/mapvbvd/mapVBVD.py#L259
