### ISSUE TITLE
Circular import for torch.optim and einops

### ISSUE THREAD

**Issue by koflera** [PTB-MR/mrpro#132]
when importing defining optimization routines such as LBFGS or Adam, we are currently experiencing an input-warning that apparently seems related to

[(https://github.com/pytorch/pytorch/pull/111802)]

Thus, in the test we expect the input warning. LBFGS however seems to run and for a few preliminary tests, also to provide the expected results

**Comment by ckolbPTB** [comment]
Does not seem to be a problem anymore.
