### ISSUE TITLE
conjugate gradient method

### ISSUE THREAD

**Issue by ckolbPTB** [PTB-MR/mrpro#14]
Implement conjugate gradient approach

`IData = cg(H:LinearOperator, b:Tensor, num_it:int)`

Check list:
- [ ]     Create branch
- [ ]     Implement code
- [ ]     Add comments
- [ ]     Implement tests
- [ ]     Squash commmits
- [ ]     Create PR
- [ ]     Assign reviewer(s) to PR

**Comment by fzimmermann89** [comment]
I am wondering if we can make use of https://github.com/guanhuaw/MIRTorch ?
