### ISSUE TITLE
Package name does not match PEP8

### ISSUE THREAD

**Issue by schuenke** [PTB-MR/mrpro#156]
Our package name is currently "**MRpro**" with two capital letters at the beginning, but the official style guide for Python code (PEP8) recommends "short, all-lowercase names" for packages and modules. Find the corresponding section [HERE](https://peps.python.org/pep-0008/#package-and-module-names)

Thus, imo, we should change the python package name, but keep the name with leading capital letters in the Readme / docs etc...

**Comment by fzimmermann89** [comment]
Isn't our package name already mrpro?

As in 'import mrpro'?

Nevertheless, I fully agree also a pypi and conda package should use exactly the same spelling as we use in our code. So mrpro.

(I would even be ok with also changing the spelling everywhere and just use lower case letters even in the Readme etc...)

**Comment by schuenke** [comment]
In the pyproject.toml we currently define:

```toml
[project]
name = "MRpro"
version = "0.0.1"
```

and I realized that `mrpro` / `MRpro`  was the only package with capital letters when I set up my new env.

**Comment by fzimmermann89** [comment]
Yeah, let's get rid of the capitalization
