### ISSUE TITLE
Shape of acq_info.idx.user -> switch to separate user_0, user_1, etc?

### ISSUE THREAD

**Issue by fzimmermann89** [PTB-MR/mrpro#158]
Almost all `acq_info.idx` have shape `[other, k2, k1]`, only user is of shape `[other, k2, k1,8]`.
Do we maybe instead want split it into 8 different idx and have all acq_info idx have the same shape?
Otherwise, `user` would always either need a special case (or use up the ellipses in a rearrange..)

(I think I just decided at some point while implementing acqinfo to have the user_idx as one tensor and now regret the decision -- what are your opinions?)

**Comment by fzimmermann89** [comment]
The other option would be to make everything in acq_info of shape [other, k2, k1,X] with X 1,8 (user_idx), 16(channel_mask) etc..
I kind of dislike that the last number of dimensions differs between tensors in the acq_info struct.

**Comment by schuenke** [comment]
I think I didn't use the user indices yet, but having a consistent shape for all indices sounds reasonable to me.

**Comment by ckolbPTB** [comment]
Not sure if we are talking about acq_info.idx or everything in acq_info. For idx it would be fine to have it all in the shape [other, k2, k1] but for all the parameters in acq_info it will be cumbersome. It would therefore make more sense to me to use the [other, k2, k1, X] convention, even if X=1 for many entries.

**Comment by fzimmermann89** [comment]
So we separate out the user idx into user_1, etc and make everything else in the acq_info [..., k2, k1, X]
