### ISSUE TITLE
CsmData class

### ISSUE THREAD

**Issue by ckolbPTB** [PTB-MR/mrpro#16]
```
class CsmData(IData):
    CsmData.header (based on ismrmrd) -> check in functions if certain parameters available
    CsmData.data: torch.Tensor 5D: [everything_else, coils, z, y, x]
```
       
Check list:
- [ ]     Create branch
- [ ]     Implement code
- [ ]     Add comments
- [ ]     Implement tests
- [ ]     Squash commmits
- [ ]     Create PR
- [ ]     Assign reviewer(s) to PR

**Comment by fzimmermann89** [comment]
We decided to have the CSMData class be a QData child, not a  IData child.
