### ISSUE TITLE
Bipolar gradient

### ISSUE THREAD

**Issue by ckolbPTB** [PTB-MR/mrpro#184]
Currently we only support a single type of readout: https://github.com/PTB-MR/mrpro/blob/9b62daeb99a0bb5bb364088b4aedba37fbfdf0c8/src/mrpro/data/traj_calculators/_KTrajectoryCalculator.py#L69

For a multi-echo acquisition with bipolar readouts the readout direction (and probably centre of the readout) is different between odd and even echos.

**Comment by fzimmermann89** [comment]
Related: #50
