### ISSUE TITLE
Cartesian acquisition model

### ISSUE THREAD

**Issue by ckolbPTB** [PTB-MR/mrpro#19]
Create Cartesian acquisition model

Check list:
- [ ]     Create branch
- [ ]     Implement code
- [ ]     Add comments
- [ ]     Implement tests
- [ ]     Squash commmits
- [ ]     Create PR
- [ ]     Assign reviewer(s) to PR

**Comment by fzimmermann89** [comment]
https://github.com/ckolbPTB/mrpro/issues/9#issuecomment-1750410990

**Comment by schuenke** [comment]
Is this resolved by #142 ?!

**Comment by ckolbPTB** [comment]
Closed by #146
