### ISSUE TITLE
Progress bars / verbose flag / callback functions / ... etc

### ISSUE THREAD

**Issue by koflera** [PTB-MR/mrpro#194]
**Current Status**: We will add a callback to optimizer. Maybe to some other long running functions with defined progress as well.

## TODO ##
Add callback to:
- [x] CG (#195) 
- [x] ADAM
- [x] LBFGS

Update: we decided that it is not ot needed for 
- [ ] Direct Reconstruction of many 'others' ?  (#183)

## Original Issue ##

> For algorithms, it might be nice to have an option to be able to track some information when running the routine. 
> For example, for CG, it migh bi interesting to check the current residual, for adam/lbfgs/... the value of the loss function, etc.
> 
> Should we maybe start to add something like a `verbose` flag for algorithms?

**Comment by fzimmermann89** [comment]
For low-level algorithms, I would not add a progressbar or output, but instead a callback, similar to what scipy does (https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html):
You can specify a function that will be called after each iteration with the current parameters.

For  higher level algorithms, such as 'CG - Sense Reconstruction', 'Superresolution-Reconstruction' etc I would agree that a verbose flag with progress bars is helpful.

**Comment by fzimmermann89** [comment]
The advantage of a callback over a verbose setting is, that most of the time, I would assume, we either
a) run in vscode with a debugger and can use its logging/debugging functions or
b) we run something that takes longer from the terminal, where a general verbose would just print difficult to parse information to stdout. 

Either way, what would a good 'verbose' be for a low-level algorithm?
A callback could instead use a problem dependent logging which is set at the higher level,  for example:
```
def callback_neptune(x):
   neptune_run['current_residual'].append(f(x))
```

An open question for me is what the signature of the callback should be:
Is it aways just a single tensor with the current estimate, or something more involved such as a 
(current_x, other_algorithm_dependend_stuff_as_dict) ?  or always a dict, with guaranteed key "x" for the current solution and all other keys algorithm dependent?

Pro single tensor:
 - consistent interface for all optimizers
 
Pro More information:
 - simple debugging by (for example), setting 
 `callback=lambda infos:print(infos['beta'])`

 Disadvantage:
 - different algorithms will return different information, so to fully allow mypy in user code, we need a `CG_CallbackDict` type (or are there smarted ways to do the typehinting than https://mypy-play.net/?mypy=latest&python=3.12&gist=e0ac8a4cf0cd8fe00d0fdde9be582eb3

**Comment by koflera** [comment]
I am also not sure... I would say for algorithms that are specifically designed to minimize/maximize a functional, it feels that the value of this functional at the current estimate is the minimium required information to be output. Further information is without doubt inherently linked to the algorithm of choice... regarding mypy, I unfortunately lack the experience to have an opinion :D

**Comment by fzimmermann89** [comment]
Add callback to:
- [x] CG (#195) 
- [ ] ADAM
- [ ] LBFGS
- [ ] NUFFT ?? (#162)


For NUFFT, this would require looking at the looping logic used inside torchkbnufft..

**Comment by ckolbPTB** [comment]
Maybe something like:

```
from typing import TypedDict

class OptimizerStatus(TypedDict):
    solution: torch.Tensor
    iteration_number: int
    
class CgStatus(OptimizerStatus):
    solution_update: torch.Tensor
    objective_value: float # maybe this can be part of the parent class because we probably always want that?
    
def cg_print_current_status(current_status: CgStatus):
    """callback function which doesn't make any sense"""
    print(f'It {current_status['iteration_number']}: {current_status['solution']} + {current_status['solution_update']} - obj: {current_status['objective_value']}')
```
