### ISSUE TITLE
Discussion: Variable and Parameter Names

### ISSUE THREAD

**Issue by fzimmermann89** [PTB-MR/mrpro#199]
I feel there might be a need to start a short discussion on variable names.

I would prefer to have names that are understandable and less abbreviated.
So, randomly looking through code in current main for examples
```
rb1 -> relative_b1
dat -> data
_adj_nufft_op -> adjoint_nufft_operator
prew -> prewhiten_matrix
rel_image_diff-> relative_image_difference
 numpoints -> nufft_number_of_interpolation_points (not sure, had to look into torchkbnufft docu)
hdr -> header
im or img -> image (or choose one abbreviation)
```
and many cases where we discussed during PR reviews

If we need to abbreviate to fit within the line width,  I would instead increase the line width. Often, these abbreviations are combined with a comment that explains the abbreviation. So a more telling variable could also save the need for the comment.

What are your opinions?

**Comment by schuenke** [comment]
In general I agree, but I would still stick to some really common abbreviations like "op" for operator, "img" for image, "diff" for difference etc.

However, if we do so, we should definitely always agree on one abbreviation (e.g. don't use "im" and "img") and maybe also add a list of these "common abbreviations" in our documentation.

**Comment by koflera** [comment]
I in general prefer to have more comments that explain ideas, concepts and the reason why we do something in the code in proper sentences and shorter variable names rather than longer variable names with less comments.

so for example (the first line of code that I found around that might somewhat explain what I mean)
```
# if mb>1, construct the block-diagonal operator H = diag(H1,...,H_mb) and b=[b1,...,b_mb]^T, otherwise just take the matrix
HOp_np = scipy.linalg.block_diag(*[HOp.Mat[kb].numpy() for kb in range(mb)]) if mb > 1 else HOp.Mat.numpy()
```
instead of 
```
# construct numpy matrix
h_operator_numpy = scipy.linalg.block_diag(*[h_operator.matrix[kb].numpy() for kb in range(number_of_mini_batches)]) if number_of_mini_batches> 1 else h_operator.matrix.numpy()
```

I think especially when code lines tend to get longer, having longer variable names reduces the readibility and having longer comments helps.

**Comment by fzimmermann89** [comment]
This is not an operator, it is a matrix.

Your comment only explains what your code does verbatim. Not why.

```pyrhon
# scipy requires x and b to be (N,1) and the operator to be a  (N, N) matrix. 
# Thus we  stack the batches of b and x and form a block diagonal matrix. 
x=rearange(x, 'batch n-> (batch n) 1)
matrix=scipy.linalg.block_diag(*h_op.matrix.numpy())
```


This IMHO is way more readable than having go know what mb kb and Mat are

**Comment by fzimmermann89** [comment]
Also, batchsize instead of number_of_mini_batches as that's what it actually is.. ;)

**Comment by koflera** [comment]
ok, that maybe was not the best example of a comment that well explains why we want to do something, and also, the `h_operator_np` is indeed a matrix.

**Comment by koflera** [comment]
all I want to say is that I in general prefer longer comments and shorter variable names... 
One can probably come up with arbitrary examples which support the one or the other flavour ;)

**Comment by koflera** [comment]
> Also, batchsize instead of number_of_mini_batches as that's what it actually is.. ;)

haha, true ;)

but still... i think 

`h_matrix_numpy = scipy.linalg.block_diag(*[h_operator.matrix[kb].numpy() for kb in range(number_of_samples)]) if number_of_samples> 1 else h_operator.matrix.numpy()`

is still way longer than
`
h_mat_np = scipy.linalg.block_diag(*[HOp.Mat[kb].numpy() for kb in range(nb)]) if nb> 1 else HOp.Mat.numpy()`

and not easier to read just because of the more explicit names of the variables.

**Comment by fzimmermann89** [comment]
A lot of the lenghtyness of the line is unrelated to the variable names and actually due to the range loop over the first dimension instead of unpacking, see the alternative above.. 

But to understand that this is true, one needs to know that mb is the batch size and the loop goes over all elements of the matrix which is not immediately visible. 

The H on the other hand in Hop doesn't convey any meaning in the context you probably want to use this line in. There will ever be only one operator in this test. That you named it H is irrelevant.

So operator and blockmatrix will be more descriptive than the cryptic h_mat_np and not that much longer. 


I think good variable names can make code much more self documenting than abbreviations. 

I agree that for some common words we might want to allow fixex abbreviations, such as _acq_ and _op_ but mb is IMHO never a good name for a variable.

**Comment by schuenke** [comment]
With #214 our naming convention was included in the [contributor guide](https://ptb-mr.github.io/mrpro/contributor_guide.html).

IMO this can still be extended, but in general we made a decision and this Issue can be closed, no?!
