### ISSUE TITLE
2D radial acquisition model

### ISSUE THREAD

**Issue by ckolbPTB** [PTB-MR/mrpro#20]
Create acquisition model for 2D radial scans

Check list:

- [ ]     Create branch
- [ ]     Implement code
- [ ]     Add comments
- [ ]     Implement tests
- [ ]     Squash commmits
- [ ]     Create PR
- [ ]     Assign reviewer(s) to PR

**Comment by fzimmermann89** [comment]
https://github.com/ckolbPTB/mrpro/issues/9#issuecomment-1750410990

**Comment by ckolbPTB** [comment]
close by PR #104
