### ISSUE TITLE
Discussion: General style of comments

### ISSUE THREAD

**Issue by fzimmermann89** [PTB-MR/mrpro#200]
I feel like there are two different styles of commenting used in our project:

- Create sections of code

```
# create PyPulseq Sequence object and read .seq file
seq = pp.Sequence()
seq.read(file_path=str(self.seq_path))


 # Create reference coil sensitivities
  csm_ref = birdcage_2d(num_coils, im_dim)


# Create operator and apply
  FFOp = FastFourierOp(recon_shape=recon_shape, encoding_shape=encoding_shape)
  (Ax,) = FFOp.forward(x)
  (AHy,) = FFOp.adjoint(y)


  # Create random noise samples
  knoise_data = torch.randn(1, ncoils, 1, 1, nkx, dtype=torch.complex64)
  
      # calculate dcf
    dcf = DcfData.from_traj_voronoi(ktraj)
```
- Comment why something needs to be done or if the code is not obvious

```    # Due to discretization artifacts the reconstructed image will be different to the reference image. Using standard
    # testing functions such as numpy.testing.assert_almost_equal fails because there are few voxels with high
    # differences along the edges of the elliptic objects.
    assert rel_image_diff(torch.abs(idat_rec), idat[:, 0, ...]) <= 0.05
```  

Imho the the first only makes sense if either the blocks are large not it is not immediately obvious what the final goal is (example: NOT` set  header values ` followed by `set image values` -> BUT: `create random ismrmrd data with valid encoding matrix in header`).  Or in examples as titles for different notebook cells.

Either way, it could be nice to move closer to a common style, as some functions have for each couple of lines these section comments, some don't, what do you think?

**Comment by koflera** [comment]
I, to be honest, like the combination of the two :D
While comments of the second type are a must, in my opinion, I typically also like to see some structure that arises from comments like the in the first case. I agree that they might not be super useful sometimes, but I have the feeling that from those comments one is also immediately able to see what one could skip in reading.

But I also like the alternative to collect more "trivial" assignments in one bigger block as you have shown.

**Comment by ckolbPTB** [comment]
Has been adopted as much as possible.
