### ISSUE TITLE
WASABI/WASABITI shape tests not covering their purpose

### ISSUE THREAD

**Issue by schuenke** [PTB-MR/mrpro#202]
Currently the `test_WASABI_signal_model_shape` and `test_WASABITI_signal_model_shape` tests don't fully cover their purpose because all spatial dimensions are 1 in all 4 (or rather 3, because one case is duplicated) tested cases. We should change this. Maybe the [test for the t1 models](https://github.com/PTB-MR/mrpro/blob/main/tests/operators/models/test_t1_models.py) can serve as an example. 

Furthermore, after merging #193, the signal models should accept `float` instead of `torch.Tensor` for all single-value arguments. Could adjust this as well.

In addition, missing docstrings and some explaining comments should be added.

Maybe @JoHa0811 can take care of this? Best would be after #193 is merged.

**Comment by fzimmermann89** [comment]
Also, I think I forgot to both change the tests AND the models to return a tuple of tensors.... ....
