### ISSUE TITLE
Poll: Anybody using github workspaces or vscode devcontainer? 

### ISSUE THREAD

**Issue by fzimmermann89** [PTB-MR/mrpro#205]
Is anybody else sometimes using github workspaces with this repo?
I.e. the vscode that comes up if pushing ',' while on github with your browser (not to basic one that comes up if you push '.')

Or vscode devcontainers?

If yes, I will consider adding a devcontainer.json and a dockerfile that adds a few more basic tools to the test/binder docker that are useful for development. 
This would mean you can start right with a set up development environment without always having to install mrpro etc if using github workspaces..

If nobody else is using it, I will most likely not spend any time on it.

So, give a thumbs up if you might benefit from it.

**Comment by schuenke** [comment]
I am currently not using it because I would have to pay for it not having a student account, no? This is why I never really looked into it. Not sure if I would use it...

**Comment by ckolbPTB** [comment]
not possible thanks to IT anyway
