### ISSUE TITLE
ConstraintOp silently produces wrong result if bounds length does not match parameter length

### ISSUE THREAD

**Issue by fzimmermann89** [PTB-MR/mrpro#206]
ConstraintOp will only return so many parameters as there are bounds set.

This is unexpected and would cause our tests to fail (if the optimizer test would actually run)

**Comment by fzimmermann89** [comment]
Is this expected and should be documented and the test be changed?

Or should it be fixed in the operator?

**Comment by fzimmermann89** [comment]
I changed it, such that given N bounds and M parameters it will always return M parameters.
 if M>N, the last M-N parameters will be unconstrained and 
 if N>M, the last N-M bounds will be unused.

**Comment by ckolbPTB** [comment]
Should we not return an error of N != M? If the number of bounds does not match the number of parameter, it seems more likely that the user made a mistake in setting the bounds rather than intended behaviour.

**Comment by fzimmermann89** [comment]
True.
But then I would prefer a shortcut for 'No bounds'  that is shorter than setting (None, None) for all parameters.

Would you be ok with
- a single None meaning no bounds on the parameter, example: bounds=(None, (0, 1), None)
- an explicit ellipses meaning 'None for all other paramters, example: bounds=((0, 1),...)  would mean only constraint first parameter. Only a single ellipses is allowed, as in array indexing.

**Comment by ckolbPTB** [comment]
I would prefer bounds=(None, (0, 1), None). This to me is self-explanatory.

bounds=((0, 1),...) seems to me of very limited use because there is no reason why a user would be more likely to put bounds on the first parameter and not the others.

**Comment by fzimmermann89** [comment]
Ah sorry, imprecise question.
I was asking if you were ok with me implementing either (option 1) or (option 1 AND option 2).

The first question was if we are ok with users being lazy and only specifying a single None for no bounds (It seems you are ok with that, and I will implement it in a separate PR)

Option 2 would be a way to explicitly specify: Only put bounds on the first parameter, but pass on all other parameters. This would be a way to enable the behavior I initially used to address the issue. Thus, the second question was if this additional functionality would create to much complexity and we should always force to set the correct number of bounds, thus if we vote against implmenting also the logic for option 2.
I was playing around with the optimizers and found thought it would be quite usefull to allow writing "constrain only the second to last parameter" as `bounds=(...,(0,1), None) `, similiar as I am used to with array indexing or einops...

**Comment by ckolbPTB** [comment]
Option 2 would be nice but sounds like a lot of work. I would be completely happy with option 1 and let the user add a few `None` s themselves.
