### ISSUE TITLE
Create test data

### ISSUE THREAD

**Issue by ckolbPTB** [PTB-MR/mrpro#21]
Create test data for unit tests.

Check list:
- [ ]     Create branch
- [ ]     Implement code
- [ ]     Add comments
- [ ]     Implement tests
- [ ]     Squash commmits
- [ ]     Create PR
- [ ]     Assign reviewer(s) to PR

**Comment by ckolbPTB** [comment]
Can we somehow use test data creation functions of ismrmrd: e.g. https://github.com/ismrmrd/ismrmrd-python/blob/master/tests/test_common.py  -> No. Copy and modify code.

**Comment by fzimmermann89** [comment]
I want to suggest using pytest for testing and fixtures to generate the data necessary

https://docs.pytest.org/en/6.2.x/fixture.html#quick-example

@schuenke @schote (or whoever else has opinions regarding tests): What do you think?

**Comment by schuenke** [comment]
I am not 100% sure if I understood the advantage of the fixtures, but I also don't see any disadvantages aside from the additional third party package. So for me using pytest would be fine. Maybe somebody else (e.g. @JoHa0811) has a stronger opinion?

**Comment by fzimmermann89** [comment]
> Can we somehow use test data creation functions of ismrmrd: e.g. https://github.com/ismrmrd/ismrmrd-python/blob/master/tests/test_common.py -> No. Copy and modify code.

The file above only creates random acquisition. 
This is in 88da941556112074d71a59f3242f255c568c1719 and used by 51bf7e6eba4032e871f24d66f99b92ed8f13a6d7

Biggest issue is the header.
Here we should missing information to get good coverage.
Or maybe fixup some existing 'create random XML given the xsd schema' code to fuzz the header parsing.


Also maybe useful:
https://github.com/ismrmrd/ismrmrd-python-tools/blob/17fe6fbf1bb645112e2ad0023eb4f42afb36421e/generate_cartesian_shepp_logan_dataset.py
which creates matching information and useful data

**Comment by fzimmermann89** [comment]
... which, btw, is also copied at https://github.com/kspaceKelvin/python-ismrmrd-server/blob/master/generate_cartesian_shepp_logan_dataset.py

and might be what @ckolbPTB had in mind.

I'd argue to copy it to our repo as well and make it a pytest fixture :D

**Comment by ckolbPTB** [comment]
I was thinking of this: https://github.com/ismrmrd/ismrmrd/blob/master/utilities/generate_cartesian_shepp_logan.cpp
which is also used for some conda tests in ismrmrd: https://github.com/ismrmrd/ismrmrd/blob/master/conda/run_test.py

The advantage of generate_cartesian_shepp_logan_dataset.py would be that we could modify it to also provide non-Cartesian data sets and hence would give us more options for testing.

**Comment by fzimmermann89** [comment]
Good point.

Another of using the python code as a starting point would be that it is easier to create edge case tests as well. For example missing header fields etc..

(And we could, for now, avoid any c dependency, making it easier to run the tests on windows as well)

**Comment by ckolbPTB** [comment]
Starting to implement python-based ismrmrd testdata creation here: https://github.com/ckolbPTB/mrpro/tree/ismrmrd_test_data
