### ISSUE TITLE
Move Iterative Walsh to algorithms? 

### ISSUE THREAD

**Issue by koflera** [PTB-MR/mrpro#210]
I would suggest to move `iterative_walsh` 

https://github.com/PTB-MR/mrpro/blob/9abccff816a5a55d657cfb592af69e08f96dac56/src/mrpro/data/_CsmData.py#L29

to algorithms... having it in `CsmData` feels like suggesting that is the standard algorithm of choice, but we might also want to use something else, like espirit etc.

Also, given that iterative walsh seems to mainly work using a power-iteration, I would suggest to implement a general class for a power-iteration method (we will need this anyway for other algorithms as well) and to use that for iterative-walsh.

what do you think?

**Comment by fzimmermann89** [comment]
1. Re Power iteration: Yes, see #97 . 
I would set the parameters, docstring and return values as a eigenvector/eigenvalue solver
So not only return some b_k, but also calculate the eigenvalue.
I think it would be nice  to have the "A" either being or callable or a LinearOperator. As this will be used in different other algorithms, it might make sense not to force us to create a linearoperator for each function we might use inside the power iteration. And we ever only need the forward application anyways...

2. Move iterative_wash: 
I am a bit undecided. It could also be nice to have all the csm algorithms attached to csm, the dcf algorithms attached to dcf, etc. 

Another datapoint: I am currently implementing a Rotation class, which also contains a lot of "algorithms" (conversion from quaternions to euler angles, multiplication of quaternions, ....) and I would not move these to algorithms as they will only ever be used in the Rotaiton class... although they are similar to the csm and dcf ones.

But I would also be fine with moving the csm and dcf algorithms to an `algorithms/csm `... folder and only have the _from... 
in the data classes. If we do this, I think the algorithms should the be "hidden" via underscores and not be a part of the public API and always be accessed through the classmethods of the CSMData class

**Comment by ckolbPTB** [comment]
I also agree with the power iteration part but I do think that "_iterative_walsh", "_espirit"... should stay with CsmData because it does not really make sense to use them anywhere else and for most MR people this would be the first place they look.

**Comment by koflera** [comment]
> 1. Re Power iteration: Yes, see [move largest EW/EV estimation into function #97](https://github.com/PTB-MR/mrpro/issues/97) .
>        I would set the parameters, docstring and return values as a eigenvector/eigenvalue solver
>        So not only return some b_k, but also calculate the eigenvalue.
>        I think it would be nice  to have the "A" either being or callable or a LinearOperator. As this will be used in different other algorithms, it might make sense not to force us to create a linearoperator for each function we might use inside the power iteration. And we ever only need the forward application anyways...

I would prefer to force the input to be a LinearOperator. First, the operator-norm only makes sense anyway if the operator is linear. Second, if the matrix-representation of the linear operator is not a squared matrix, we need the adjoint of the operator as well to compute the operator norm, see e.g.

https://odlgroup.github.io/odl/generated/odl.operator.oputils.power_method_opnorm.html

Alternatively, we could also raise an error and let the user pass some sort of normal-operator (#196) in that case.

**Comment by fzimmermann89** [comment]
I would prefer a simple power iteration that only calculates the eigenvector, maybe the eigen value and works with both linear operators and arbitrary callables.
By definition, this will only work for square linear operations, but it should be usable within vmap and the resulting Walsh code should be simpler than the current one. 

For the operator norm, I would add second function that calculates the operator norm for linear operators using the power iteration.
