### ISSUE TITLE
PyTest fixture definitions/locations

### ISSUE THREAD

**Issue by schuenke** [PTB-MR/mrpro#211]
Currently, we have a single `conftest.py` file in our main `tests` directory including the majority of our fixtures.

However, some fixtures are defined directly in our test files (e.g. https://github.com/PTB-MR/mrpro/blob/9abccff816a5a55d657cfb592af69e08f96dac56/tests/data/test_kdata.py#L71), although they are used in other test files (in this case for example in https://github.com/PTB-MR/mrpro/blob/9abccff816a5a55d657cfb592af69e08f96dac56/tests/utils/test_modify_acq_info.py#L22)

If a fixture is not in `conftest.py`, we have to import it.
However, Ruff will detect and remove these imports as unused.

My suggestions would be to move ALL fixtures into `conftest.py`, but to make use of the possibility to have [multiple `conftest.py` files in multiple nested directories](https://docs.pytest.org/en/7.1.x/reference/fixtures.html#conftest-py-sharing-fixtures-across-multiple-files) to prevent the main `conftest.py` file to get to overcrowded and chaotic:

 
>  You can have multiple nested directories/packages containing your tests, and each directory can have its own conftest.py with its own fixtures, adding on to the ones provided by the conftest.py files in parent directories.

**Comment by ckolbPTB** [comment]
**General**
- [x] include _PulseqRadialTestSeq in tests/data/__init__.py? 
- [x] include _OptimizationTestFunctions in tests/operators/__init__.py 
- [x] create_traj from tests.data.test_trajectory.py used in operators/test_cartesian_sampling_op.py, operators/test_fourier_op.py -> move to conftest
- [x] include _EllipsePhantomTestData in tests/phantoms/__init__.py

**Conftest**
only used in tests/operators/models:
- [x] SHAPE_VARIATIONS_SIGNAL_MODELS
- [x] create_parameter_tensor_tuples 

only used in tests/data
- [x] cartesian_grid 
- [x] random_mandatory_ismrmrd_header 
- [x] random_acq_info 
- [x] random_test_data 
- [x] dcm_2d 
- [x] dcm_multi_echo_times 
- [x] dcm_multi_echo_times_multi_folders


Note: Issue in test_kdata.py/test_modify_acq_info.py has already been solved in previous PR
