### ISSUE TITLE
docstring 'optional' inconsistency

### ISSUE THREAD

**Issue by fzimmermann89** [PTB-MR/mrpro#213]
We sometimes have 'optional' in the docstrings if arguments have default values, but most of the time not.

Should we add 'optional', keep it as is or remove it?

I would prefer to remove it, as
1. it is already set by having a default argument 
2. easy to forget to add or change if the signature changes.
3. the convention comes from a time before type hints and to show, for example that something set to None means default value.

For me , all the arguments as for NOT putting the types in the docstring hold: We don't have to manually add the same information twice.

**Comment by schuenke** [comment]
I still like the additional 'optional' in the docstring, but agree that it is easy to forget and probably very difficult to check for. Thus, for a better consistency, I would also agree to remove it.
