### ISSUE TITLE
Wrong shapes in wasabi test

### ISSUE THREAD

**Issue by fzimmermann89** [PTB-MR/mrpro#227]
https://github.com/PTB-MR/mrpro/blob/b5640d07ee25eff7952c05851d7fdf5595bc8112/tests/operators/models/test_wasabi.py#L6

Is this on purpose?
only one of the parameter maps is of the expected number of dimensions for us..

**Comment by schuenke** [comment]
this is also related to #202, but should be fixed with #231 and #226, no ?!
