### ISSUE TITLE
Warning for FourierOp for Cartesian data without CartesianSamplingOp

### ISSUE THREAD

**Issue by ckolbPTB** [PTB-MR/mrpro#228]
The FourierOp applies a FFT along Cartesian direction even if they have not previously been resorted correctly with the CartesianSamplingOp. This leads to wrong voxel size/dimensions. 

Suggestion: Check in FourierOp  if FFT can be applied (centered k-space, correct sorting of data points) otherwise use NUFFT. Print warning to suggest that it might be faster to use CartesianSamplingOp before calling FourierOp

Challenge: How to figure out if FFT can be applied...

**Comment by fzimmermann89** [comment]
a) For devciding if FFT or NUFFT, the Fourieroperator should test if all differences between k-space points is 1. 
For an FFT to work, we dont need the points to be on an integer grid.
We need that the difference between neighbouring points is constant and that the k-space center is either in the array center.

b)  I would like some function that sorts the Kdata and trajectory once if possible, avoiinding many sorts- and unsorts in CG.
So in the reconstruction method, we would call this function once, and if the data can be sorted, it would sort the KData.data and KTrajectory and we would continue with sorted KData in the reconstruction, Was there some issue with this approach I forgot about?

**Comment by ckolbPTB** [comment]
Add a) this is only true if the CartesianSamplingOp is not applied. If it is going to be applied or not is not known when we create the FourierOp so there is imo no way we can choose the nufft for unsorted Cartesian correctly.

Add b) presorting we discussed before with the challenges of (i) potentially very large datasets with lots of 0s and (ii) the need of a mask inside CG to select acquired kspace points.

**Comment by fzimmermann89** [comment]
Ah ok, so the Fourier operator should check if the k space data is consecutive. If not, it should use a composition of FFT and Sorting Op...

For presorting, we would need a function that also changes the Trajectory. It should be similar as the remove oversampling preprocessing..
