### ISSUE TITLE
Docker Cache 

### ISSUE THREAD

**Issue by fzimmermann89** [PTB-MR/mrpro#244]
Not sure if it applies, just came across
 https://blacksmith.sh/blog/cache-is-king-a-guide-for-docker-layer-caching-in-github-actions

Tldr

   - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: user/app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

For caching layers

**Comment by schuenke** [comment]
Sounds good and looks like a very simple thing to try 👍

**Comment by ckolbPTB** [comment]
I dont think this will work for us. The caching is only done based on the docker-related files. If we change e.g. the package requirements in pyproject.toml then this is not detected by the caching system and no new container is build. 

In any case, we have only one layer to ensure the container is as small as possible. Therefore there are no layers which could be reused from cache.
