### ISSUE TITLE
__repr__ for our dataclasses

### ISSUE THREAD

**Issue by ckolbPTB** [PTB-MR/mrpro#250]
Currently when we do someting like
```
idata = IData.from....
print(idata)
```
then we get a lot of mainly useless information. It would be nice if this print statement would lead to some helpful information, e.g. 
_IData with shape [1 1 20 30 40]_

This would require to implement `__repr__` method for our dataclasses. See e.g. https://www.pythontutorial.net/python-oop/python-__repr__/

**Comment by ckolbPTB** [comment]
Suggestion:

IData -> IData with shape [...], FOV [...], TE, TR, TI and flip angle
QData -> QData with shape [...] and FOV [...]
KNoise/DcfData -> KNoise/DcfData with shape [...]
KData -> KData with shape [...], trajectory shape [...], FOV, TE, TR, TI and flip angle, encoding_matrix, recon_matrix

**Comment by fzimmermann89** [comment]
I would suggest to put fov, te etc. in kheader repr.

And in kdata return
Kdata instance: (shape, dtype) and header.repr

**Comment by ckolbPTB** [comment]
check default `__repr__` for dataclasses and what can be reused
