### ISSUE TITLE
Units of class attributes

### ISSUE THREAD

**Issue by schuenke** [PTB-MR/mrpro#26]
Currently, some of our class attributes (e.g. KHeader.recon_fov) are neither in SI units, nor the used unit is added to the name of the attribute. 

For the Inhommcor project we decided (https://github.com/ckolbPTB/InhomCorr/issues/15) that we:

-     always use SI units and mention it in the documentation
-     keep the attribute names without units, but mention the units in all docstrings
-     in our code, add some comments about units where it might be useful (e.g. if dB0 is in Hz or ppm)

IMO, we should do the same for the MRpro project

**Comment by fzimmermann89** [comment]
I am pretty much in favor of using SI units everywhere and only in print outs / messages etc. where we can specify the unit convert to the commonly used ones.

But just to make sure we are all on board 100%, maybe the most controversial ones are:
```
TE will be in s.
FA will be in rad.
FOV in m.
```
Can we do a thumbs-up (=SI is fine ) / thumbs-down (prefer something else, please comment with a suggestion) decision?

**Comment by fzimmermann89** [comment]
Tagging some people who might have opinions:
@chaigner @ckolbPTB @schuenke @schote  @SimoneHufnagel @mxlutz 

Of course, feel we to voice you opinion even if I didn#t tag you.

**Comment by mxlutz** [comment]
I agree with TE in s and FOV in m.

With FA I kind of prefer degree, this is what also use in protocols on the scanner and I guess its more intuitive for some people. Maybe just give this comment a Thumps up for degree and a Thumps down for rad

**Comment by schuenke** [comment]
For consistency, I would prefer to use SI units everywhere, although I agree that flipangle in deg is a bit more intuitiv. What we could do is to define another property like `flipangle_deg` that is calculated from the attribute `flipangle` on request.

**Comment by schote** [comment]
I would also stick to SI units, but I don't have an opinion about FA
