### ISSUE TITLE
Structured Data VS Lists or Tensors

### ISSUE THREAD

**Issue by fzimmermann89** [PTB-MR/mrpro#27]
There are some parts of the KData code where Tensors or Lists are used to save values, and the different positions in the tensor have different meaning.

An example are/were the Encoding Limits. Patrick and I just changed Tensors of [min, max, center] to use a dataclass instead. So you would write EncodingLimit.max instead of having the magic index number 1.

Other places currently are FOV and similar. These have .x, .y, .z fields in ismrmrd but we currently convert them to Tensors.

I'd suggest to either reuse the ismrmrd dataclass or our own dataclass for these as well.

(If we really want to be able to use them like tensors, we could add a __as_tensor__ or astuple to the dataclass definition. But IMHO code is easier to read if you don't have to remember at which position in a list or tensor what information is stored but instead use names to access the data.)

This is a general decision to be made as this question will come up in the future for different kinds of data.
What do you think? Any opinions in one or the other direction?

**Comment by ckolbPTB** [comment]
Yes, that is a good idea especially for the limits but also for the FOV and similar parameters. I would not add `as_tensor` because on the one hand a user would expect this to return [x, y, z] but our ImageTensors have the form [dim4, coils, z, y, x] so there would be a mismatch. 

I would be in favour of our own dataclass for this.

**Comment by schote** [comment]
I agree, using dataclasses is more intuitive. I might be wrong, but are there many usecases where you need fov as a tensor?
