### ISSUE TITLE
DirectReconstruction fails for unsorted Cartesian data

### ISSUE THREAD

**Issue by ckolbPTB** [PTB-MR/mrpro#288]
Currently the DirectReconstruction does not utilise the CartesianSamplingOp

**Comment by fzimmermann89** [comment]
Why does it fail? I thought it would just be slow as it would use the nufft if the data is unsorted?

Did we break something there?

**Comment by ckolbPTB** [comment]
True, it won't fail but it will reconstruct an incorrect image. If the data is unsorted our logic will still recognise that the points lie on a Cartesian grid and apply a fft but as the points are not sorted into the grid properly the output will not be correct.

This is related to #228 but so far I could not come up with any idea of how to detect when the warning message suggest in #228 needs to be provided.

We could think of always creating and applying a CartesianSamplingOp in FourierOp. Or creating a new Operator which combines both? Open to suggestions...
