### ISSUE TITLE
FastFourierOperator with spatialdimension for shapes might fail

### ISSUE THREAD

**Issue by fzimmermann89** [PTB-MR/mrpro#316]
original_shape: Sequence[int] | None = [int(astuple(recon_matrix)[d]) for d in dim]

Will fail if d in not in (-1,-2,-3) but the check is one line further down.

Addintional line reference:
https://github.com/PTB-MR/mrpro/blob/0730e0608366b422c59c0c5ffa50a94fba671cf2/src/mrpro/operators/FastFourierOp.py#L82
and probably also here:
https://github.com/PTB-MR/mrpro/blob/0730e0608366b422c59c0c5ffa50a94fba671cf2/src/mrpro/operators/FastFourierOp.py#L93

**Comment by ckolbPTB** [comment]
as a first step add a test which fails because of this issue
