### ISSUE TITLE
user idx 5 and 6 in siemens ismrmrd data

### ISSUE THREAD

**Issue by fzimmermann89** [PTB-MR/mrpro#32]
the siemens to ismrmrd converter seems to abuse these for storing something that is not an acqIdx:
https://github.com/ismrmrd/siemens_to_ismrmrd/issues/114
https://github.com/ismrmrd/siemens_to_ismrmrd/blob/545ee4dfb39db491f4d19e5b843225d08f216ae4/main.cpp#L1176

Do we remove these from our code?
Do we detect this case and unset them?

Our AcqIdx should have to same meaning for Philips and siemens data...

**Comment by ckolbPTB** [comment]
Ignore user idx 5 and 6 and print warning

**Comment by ckolbPTB** [comment]
maybe ignore here and print warning:
https://github.com/PTB-MR/mrpro/blob/0730e0608366b422c59c0c5ffa50a94fba671cf2/src/mrpro/data/AcqInfo.py#L158

and then add user labels to `KDIM_SORT_LABELS`
https://github.com/PTB-MR/mrpro/blob/0730e0608366b422c59c0c5ffa50a94fba671cf2/src/mrpro/data/_kdata/KData.py#L46
