### ISSUE TITLE
Add continuous deployment (CD) pipeline

### ISSUE THREAD

**Issue by schuenke** [PTB-MR/mrpro#328]
An automatic deployment to PyPi and conda would be great in the future. We still need to discuss:

- when should this be triggered (push to main / taged pushed / etc)
- do we want to give automatic versioning a try?
- do we want to create automatic changelogs?
- which conda server do we want to use? conda-forge? requirements for that?
- ...

**Comment by ckolbPTB** [comment]
linked to #125
