### ISSUE TITLE
Update README: add some content

### ISSUE THREAD

**Issue by schuenke** [PTB-MR/mrpro#329]
At the moment our README / landing page is pretty empty and we should start thinking about a style / structure that we want to use here. Different big packages like [numpy](https://github.com/numpy/numpy/blob/main/README.md) or [pytorch](https://github.com/pytorch/pytorch/blob/main/README.md) do this completely different. 

Personally, I prefer a more extensive version with more content and examples in the README.

**Comment by fzimmermann89** [comment]
Some ideas:
Short description what it does.
Coarse overview of functionality
1-2 short code examples (only the important 4-5 lines each), with links to full binder example notebooks.
Documentation should be easier to see.
PIP instructions to install.


Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
From: Patrick Schuenke ***@***.***>
Sent: Tuesday, July 2, 2024 8:26:50 AM
To: PTB-MR/mrpro ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [PTB-MR/mrpro] Update README: add some content (Issue #329)


At the moment our README / landing page is pretty empty and we should start thinking about a style / structure that we want to use here. Different big packages like numpy<https://github.com/numpy/numpy/blob/main/README.md> or pytorch<https://github.com/pytorch/pytorch/blob/main/README.md> do this completely different.

Personally, I prefer a more extensive version with more content and examples in the README.
