### ISSUE TITLE
Clean optional dependencies

### ISSUE THREAD

**Issue by schuenke** [PTB-MR/mrpro#338]
Currently we still list a lot of dependencies in our `pyproject.toml`:

```toml
[project.optional-dependencies]
test = [
    "coverage",
    "codecov",
    "pre-commit",
    "pytest",
    "pytest-cov",
    "pytest-xdist",
]
lint = ["mypy", "flake8", "isort", "pre-commit", "autopep8", "pydocstyle"]
docs = ["sphinx", "sphinx_rtd_theme", "sphinx-pyproject"]
notebook = [
    "zenodo_get",
    "ipykernel",
    "ipywidgets",
    "jupytext",
    "matplotlib",
    "pip-tools",
]
```

Some of these like flake8, isort etc should not be needed anymore, because we do everything with ruff now. We should remove everything that is not really needed.

**Comment by fzimmermann89** [comment]
..and add ruff?
or remove the lint completely and only have pre-commit in it, which in turn depend installs mypy ruff etc.


.. and remove pre-comit from tests..
