### ISSUE TITLE
Potential missmatch between dependency versions in pre-commit and PyTest

### ISSUE THREAD

**Issue by schuenke** [PTB-MR/mrpro#339]
In our [pyproject.toml](https://github.com/PTB-MR/mrpro/blob/main/pyproject.toml) we define our dependencies including version limitations, e.g.
`numpy>=1.23,<2.0` or `torch>=2.3,<3.0`

In our [.pre-commit-config.yaml](https://github.com/PTB-MR/mrpro/blob/main/.pre-commit-config.yaml), we explicitly list the additional dependencies for mypy, e.g. `numpy` or `torch>=2.3.0`

This mismatch in the specified versions might actually lead to different versions being used in our tests (e.g. numpy <2.0) and in the pre-commit checks like mypy (e.g. numpy > 2.0). I realized this in my [BMCTool Repo](https://github.com/schuenke/BMCTool/pull/28), where I now use the same dependency limits in the pre-commit configuration.

Maybe we can find a better way to adjust these dependencies automatically...

**Comment by ckolbPTB** [comment]
the pre-commit is run in the py3.11 container: https://github.com/PTB-MR/mrpro/blob/main/.github/workflows/pre-commit.yml

Probably the mypy dependencies are not needed at all and hopefully #311 should then also be fine
