### ISSUE TITLE
follow numpydoc style for references

### ISSUE THREAD

**Issue by JoHa0811** [PTB-MR/mrpro#351]
Based on @ckolbPTB comment in issue #192 

should we follow e.g. official numpydoc style for references:
https://numpydoc.readthedocs.io/en/latest/format.html#references
as we did here
https://github.com/PTB-MR/mrpro/blob/0730e0608366b422c59c0c5ffa50a94fba671cf2/src/mrpro/utils/Rotation.py#L640

_Originally posted by @ckolbPTB in https://github.com/PTB-MR/mrpro/issues/192#issuecomment-2189315333_

**Comment by fzimmermann89** [comment]
related: #336
