### ISSUE TITLE
Incompatibility with PyTorch 2.4.0

### ISSUE THREAD

**Issue by schuenke** [PTB-MR/mrpro#371]
The latest version of PyTorch (2.4.0) leads to some test failures in

- test_slice_projection_op_cube_rotation()
``` 
RuntimeError: The size of tensor a (918987) must match the size of tensor b (771339) at non-singleton dimension 0
```

- test_slice_projection_op_slice_batching()
```
>       torch.testing.assert_close(dotproduct_range, dotproduct_domain, rtol=relative_tolerance, atol=absolute_tolerance)
E       AssertionError: Scalars are not close!
E       
E       Expected 3845.470703125 but got 2530.9521484375.
E       Absolute difference: 1314.5185546875 (up to 1e-05 allowed)
E       Relative difference: 0.3418355400859676 (up to 0.001 allowed)
```

- test_pickling() in test_rotation.py:
```FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.```

**Comment by ckolbPTB** [comment]
Errors in `test_slice_projection_op_cube_rotation()` and `test_slice_projection_op_slice_batching()` not reproducible on Linux.

**Comment by fzimmermann89** [comment]
Is this still an issue?
I am using pytorch 2.4 without issues.
Can we close it ? @schuenke

**Comment by schuenke** [comment]
It was still an issue for me with torch 2.4.0, but everything works fine after updating to v 2.4.1
