### ISSUE TITLE
AcqInfo Trajectory Dimension

### ISSUE THREAD

**Issue by fzimmermann89** [PTB-MR/mrpro#38]
We might want to remove this https://github.com/ckolbPTB/mrpro/blob/e1291ab4940fbcfc93404504e3794e6791795257/src/mrpro/data/_AcqInfo.py#L66

or set it always to '3' if we do our own trajectory logic anyways. 

This field only describes if the traj inside the ismrmrd file is 2 or 3 dimensional for each single readout:

float* traj_;            //Trajectory, elements = head_.trajectory_dimensions*head_.number_of_samples
                        //   [kx,ky,kx,ky.....]        (for head_.trajectory_dimensions = 2)
                        //   [kx,ky,kz,kx,ky,kz,.....] (for head_.trajectory_dimensions = 3)
                        
https://ismrmrd.github.io/apidocs/1.5.0/

**Comment by schuenke** [comment]
Given the fact that we are (currently) not using potential trajectories given in the ISMRMRD files and that the information might lead to confusion, I vote to remove it.

**Comment by fzimmermann89** [comment]
In principle I agree, but not sure when and where. If we don't read it in at all, a potential solution to #39 (using trajektory information available the ismrmrd) would have to parse the acqinfo again, leading to much duplicated code.

If we decide we will never use the ismrmrd traj data, we might remove it. But AcqInfo is so closely related to the raw ismrmrd format that it feels strange to remove one of the fields... AcqInfo is not something we will be using on later anyways, it is more or less internal to our reading-in-ismrmrd-data logic, so I'd keep it somewhat close to the actual ismrmrd data (?) 

Also, if we ever export to ismrmrd with the trajectory we would need this field as well.
So, it might be better to set it in KData.from_ismrmrd after calculating the trajectory? 

We might decide that we will always have '3' as the only allowed value after setting the trajectory and always provide kz values even for 2D data (as we have written down in one of the old pptx design documents). 

This is something we should maybe discuss a bit further, I feel like both ways are really bad.... 
So please, are there any good points or ideas?

**Comment by ckolbPTB** [comment]
Set head_.trajectory_dimensions = 3 because our trajectory is always in the form [kx, ky, kz, kx, ky,...]
