### ISSUE TITLE
Add OperatorTensorSum

### ISSUE THREAD

**Issue by ckolbPTB** [PTB-MR/mrpro#387]
Allow for the addition of a tensor with an operator, e.g. useful for Tikonov-regularised SENSE where we need `A^HA + lambda*UnityMatrix`

lambda will be broadcasted to the output of the operator if possible.

**Comment by fzimmermann89** [comment]
(And we omit the unity operator..)

**Comment by fzimmermann89** [comment]
Linearoperator + tensor is not  linear.. but it would be annoying to have a different affineoperstor class. 
Did we decide that our linear operators can be affine?
