### ISSUE TITLE
ISMRMRD Trajectory

### ISSUE THREAD

**Issue by fzimmermann89** [PTB-MR/mrpro#39]
We could also consider having a Trajectory class that reads in/prepares the Trajectory information that might be already saved inside the ismrmd file.

We should check if any of the converters write something useful there.

**Comment by ckolbPTB** [comment]
Reading out the trajectory is easy in principle (see [branch ](https://github.com/ckolbPTB/mrpro/blob/0ad62bb9cb22c4b09452b31f8e9b5e38620828a6/src/mrpro/data/_KData.py#L100)) but there are many open questions
- should this be default option for trajectory
- should the trajectory be taken as is or normalised ([-pi pi])
- should this be a TrajectoryCalculator or used if trajectory==None

For tests Cartesian trajectory is ideally already available (#13)
