### ISSUE TITLE
remove_oversampling

### ISSUE THREAD

**Issue by ckolbPTB** [PTB-MR/mrpro#4]
implement RemoveOversRo in [Functions.RemoveOversRo.py](https://github.com/ckolbPTB/PtbPyRecon/blob/master/PTBRecon/Functions/RemoveOversRo.py "‌")

`KData = remove_oversampling(KData)`

Check list:
- [ ]     Create branch
- [ ]     Implement code
- [ ]     Add comments
- [ ]     Implement tests
- [ ]     Squash commmits
- [ ]     Create PR
- [ ]     Assign reviewer(s) to PR

**Comment by ckolbPTB** [comment]
For a fully sampled readout `remove_oversampling` would be straight forward but for partial echo acquisitions less so. Maybe we should explore to integrate this into the acquisition models (#9 #19  #20)  rather than having it as a separate function.

**Comment by fzimmermann89** [comment]
A would prefer to have it as a separate function, and the 'Acquistion models' be replaced by a sequence of operators.

Could you maybe repeat what the requirements for this functionality are and then we can discuss how and where to implemet it?
AFAI-understood, we can have either phase or frequence oversampling.

- Phase oversampling can only be handled after the reconstruction (or as a last step), by cutting the FOV of the reconstructed image if recon matrix and encoding matrix do not match. (This will also be mostly a thing for cartesian , right?)

- Frequency oversampling can always be removed before the reconstruction. This will be done for each readout, so we do not have to fill on partial-fourier before we can do it.
It is just iFFT along k0, crop, FFT along k0.

- Partial fourier
partial fourier is a seperate issue that has to be dealt with. Bu there are different algorithms how to do it. I think this should be a seperate function.

- cutting of pre & post samples, in ptbpyrecon this is done in the oversampling function, but you already suggested to move this into a different part of the pipeline (#98 ). This imho also does not really fit the 'remove oversampling' scope.

**Comment by ckolbPTB** [comment]
> Frequency oversampling can always be removed before the reconstruction.

For partial Fourier there are methods to "correct" for this but these only make sense for direct reconstruction. For any iterative reconstruction it is probably best to keep the data as they are. 

For consistency we could have a `select_recon_fov` at the end of the reconstruction which deals with any kind of oversampling/resolution interpolation and returns the image as we would expect it from the scanner. The AcquisitionOperators would then only work in the encoded_space

> cutting of pre & post samples [...] This imho also does not really fit the 'remove oversampling' scope.

Agreed!
