### ISSUE TITLE
Consider removing MSEDataConsistency

### ISSUE THREAD

**Issue by fzimmermann89** [PTB-MR/mrpro#402]
We could either consider removing MSEDataConsistency and replacing all uses with L2NormSquared or changing it to an alias of L2NormSquared with different parameter names.

**Comment by ckolbPTB** [comment]
I would suggest to replace it with L2NormSquared

**Comment by fzimmermann89** [comment]
So it should be removed after #395

**Comment by fzimmermann89** [comment]
This could be a good starting point if anybody new wants to set up vscode/pre-commit/pytests etc and needs a goal as motivation :)
@lrlunin @rkcatarina @bernharb

**Comment by fzimmermann89** [comment]
New decision:

new functional

```
class MSE(L2NormSquared):
   def __init__( ....)
        super().__init__(... dividy_by_n=True)
```
 with ... all the other parameters of a functional
