### ISSUE TITLE
mypy ismrmrd and h5py errors

### ISSUE THREAD

**Issue by ckolbPTB** [PTB-MR/mrpro#44]
In my VS Code I get errors like 
"Skipping analyzing "ismrmrd.xsd.ismrmrdschema.ismrmrd": module is installed, but missing library stubs or py.typed marker  [import]"

In project.toml we have got
```
[mypy-ismrmrd]
ignore_missing_imports = true
```

This does not seem to suppress these errors. Is there something else I need to configure in VS Code or is this a Bug?

Something like this would work for me:
```
[[tool.mypy.overrides]]
module = [
    "ismrmrd.*",
    "h5py"
]
ignore_missing_imports = true
```

PS: Currently the main branch also does not seem to pass mypy checks.

**Comment by fzimmermann89** [comment]
It is indeed a bug.

Regarding your PS:
What is the error you see, it seems to work on my end....
And if there is truly a mypy check not passed, should the actions on PRs not catch that? @schuenke

**Comment by schuenke** [comment]
As mentioned in #46, our github actions are currently not triggered for PR from forked branches. Thus it might be possible that we actually have conde in main, that didn't / don't pass the pre-commit workflow. 

However, this should not happen in the future any more...
