### ISSUE TITLE
Old dataset downloaded from zenodo for T1_mapping_with_grad_acq

### ISSUE THREAD

**Issue by ckolbPTB** [PTB-MR/mrpro#459]
In 

https://github.com/PTB-MR/mrpro/blob/d396143f62bfbaed5dd9b66b86be3182f3467192/examples/t1_mapping_with_grad_acq.py#L59

we are downloading v1 of the dataset instead of v2. Easy but not safe fix would be to set dataset to "13207352". This will download v2 but not v3 if there is one.

**Comment by fzimmermann89** [comment]
Is it a bug or a feature that we download a fixed version of the data?

**Comment by ckolbPTB** [comment]
good question - I thought of it as a bug, but maybe it might actually be a feature because it allows us to update the data on zenodo and then update mrpro accordingly. Otherwise we might have the problem that we discover bugs with the updated data which would then automatically break all our test pipelines. So the easy fix would be the right fix.

**Comment by fzimmermann89** [comment]
not a bug :)
