### ISSUE TITLE
PR CI actions not running ?

### ISSUE THREAD

**Issue by fzimmermann89** [PTB-MR/mrpro#46]
Maybe I am mistaken, but I thought we intended to have mypy etc. running for PRs against `ckolbPTB/mrpro/main`

#43 did not trigger any CI actions..

I am assigning @schuenke to this issue, if he does not mind, as he configured the current CI.
Feel free to close it if this is 'works-as-intendend' and I misunderstood something..

**Comment by schuenke** [comment]
Currently, CI actions are not triggered for PRs from forked repos. @ckolbPTB should be able to change this: [LINK](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#enabling-workflows-for-forks-of-private-repositories)

**Comment by ckolbPTB** [comment]
Does anyone know if we need any of these options:

- Send write tokens to workflows from fork pull requests.
This tells Actions to send tokens with write permissions to workflows from pull requests originating from repository forks. Note that doing so will give maintainers of those forks write permissions against the source repository.

- Send secrets and variables to workflows from fork pull requests.
This tells Actions to send repository secrets and variables to workflows from pull requests originating from repository forks.

- Require approval for fork pull request workflows.
Fork pull requests from users without write access will require approval to run workflows.

**Comment by fzimmermann89** [comment]
The issues seems to be fixed, thank you!

Regarding the questions:

> * Send write tokens to workflows from fork pull requests.

No, we don't need that

> * Send secrets and variables to workflows from fork pull requests.

No.

> * Require approval for fork pull request workflows.

This would be something to consider later on, if we make use of secrets in the public repo etc. But for now, only approved users can fork the repo - so only those can send in PRs and we don't need to approve each PR.
