### ISSUE TITLE
Switch from autopep8 to black pre-commit hook

### ISSUE THREAD

**Issue by schuenke** [PTB-MR/mrpro#54]
Currently, we have set **black** as default formatter in our VSCode settings.json, but we "just" run the **autopep8** hook in our pre-commit workflow. 

I suggest to switch to the [black pre-commit hook](https://black.readthedocs.io/en/stable/integrations/source_version_control.html) to ensure that all code fulfills the black style.

I checked it locally and currently 99,x% of you code is in the "black style" already.

**Comment by fzimmermann89** [comment]
Good idea.
