### ISSUE TITLE
l2_tikonov_solver

### ISSUE THREAD

**Issue by ckolbPTB** [PTB-MR/mrpro#6]
![Image](https://user-images.githubusercontent.com/17784338/251425246-bf664420-9b98-45db-a3d0-a441278c7624.png)

Check list:
- [ ]     Create branch
- [ ]     Implement code
- [ ]     Add comments
- [ ]     Implement tests
- [ ]     Squash commmits
- [ ]     Create PR
- [ ]     Assign reviewer(s) to PR

**Comment by fzimmermann89** [comment]
This does not look like a solver, but like a Operator for the regulariyed normal Equation?
In my understanding a solver returns a solution to a problem, so solver would be CG or something?
