### ISSUE TITLE
Add PyTest warnings to coverage report comment

### ISSUE THREAD

**Issue by schuenke** [PTB-MR/mrpro#63]
I just realized that PyTest throws some warnings in #62, but these are not mentioned/shown/linked in our "coverage report comment". Sure, these are just warnings and not errors, but imo it would still be nice to see these somewhere. I didn't find an option to enable this in the readme of the GitHub repo of the tool we are using (https://github.com/MishaKav/pytest-coverage-comment) and before I forget it, I decided to create an issue. 

The warnings in this case are:
```
=============================== warnings summary ===============================
tests/data/test_idata.py::test_IData_from_dcm_file
  /home/runner/work/mrpro/mrpro/tests/data/_Dicom2DTestImage.py:44: ComplexWarning: Casting complex values to real discards the imaginary part
    self.imref = (self.imref * 2**16).astype(np.uint16)

tests/data/test_idata.py::test_IData_from_dcm_file
  /opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/pydicom/dataset.py:2249: DeprecationWarning: Starting in pydicom 3.0, Dataset.file_meta must be a FileMetaDataset class instance
    warnings.warn(

tests/data/test_ktraj.py::test_KTrajectoryRpe[random_kheader0-random_full_ismrmrd_header0-random_acquisition0]
  /opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
    return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
```

Especially notifications about _DeprecationWarnings_ could be useful.

**Comment by fzimmermann89** [comment]
Also the Complex warning is often missing .abs() ..

We can call pytest with -W options / set  the filterwarnings options in  the pyproject.toml (https://docs.pytest.org/en/latest/warnings.html) to turn certain warning classes into Errors.

We could consider treating all warnings as errors (except in test cases explicitly marked to raise a warning)

**Comment by schuenke** [comment]
Handling _warnings_ as _errors_  is a good idea imo. It can easily be done using `filterwarnings = ["error"]` in the `[tool.pytest.ini_options]` section in our _pyproject.toml_ file.

However, as far as I get it, this would also handle warnings from third party libraries (that we have no control over) as errors, which could in principle become a problem.

So far, I didn't find a general solution to ignore such third-party warnings, but in case it becomes an issue, we could simply add the corresponding package to the ignore list. For example by adding `filterwarnings = ["error", "ignore:::.*pydicom*"]` to ignore warnings from the _pydicom_ package.

Does somebody have a better solution?

**Comment by fzimmermann89** [comment]
Filtering pydicom would filter all warnings raised by pydicom. For example, if we use something that is deprecated in pydicom, we would ignore the warning, right?

I would NOT filter the warnings globally.
Instead, if we notice a certain test causes a warning by pydicom that we want to ignore, we should specifically ignore just that warning in the test. Not globally.

Do we currently get any warnings we want to ignore?

**Comment by schuenke** [comment]
> Do we currently get any warnings we want to ignore?

No, currently we don't get any, but I wanted to make sure that we are able to ignore them somehow in case this becomes an issue in the future.
