### ISSUE TITLE
Csm inati method

### ISSUE THREAD

**Issue by ckolbPTB** [PTB-MR/mrpro#64]
could be implemented via a wrapper for https://github.com/ismrmrd/ismrmrd-python-tools/blob/17fe6fbf1bb645112e2ad0023eb4f42afb36421e/ismrmrdtools/coils.py#L92

**Comment by fzimmermann89** [comment]
I believe the 'iterative' version produces different results then the one we currently use in ptbpyrecon.

- We should check it this is significant.
- Decide if we want to torchify the version (to be able to run it on a GPU for example) or keep it as numpy. 

I'd slightly prefer copying it over and torchifying over wrapping.

**Comment by fzimmermann89** [comment]
for the iterative method, see 
https://gist.github.com/fzimmermann89/7e6a1a34cdfbd27903056fff6f717f1a
(untested)

I will try to make it reproduce the results as close as possible to those of our internal ptbpyrecon

**Comment by fzimmermann89** [comment]
#161

**Comment by fzimmermann89** [comment]
Here it would be nice to test it vs. ptbpyrecon...
