### ISSUE TITLE
Make operators and pytorch.autograd work together

### ISSUE THREAD

**Issue by ckolbPTB** [PTB-MR/mrpro#68]
For most of our operators an adjoint/derivative method will be defined. pytorch.autograd should use that. If the method is not defined it should default to standard pytorch.autgrad. More details can be found in the discussion of #8.

**Comment by fzimmermann89** [comment]
This would work 
```python
import torch
from typing import Any, Callable


class _AutogradWrapper(torch.autograd.Function):
        """Wrap forward and adjoint functions for autograd."""
        
        # If the forward and adjoint implementation are vmap-compatible, 
        # the function can be marked as such to enable vmap support.
        generate_vmap_rule = True

        @staticmethod
        def forward(fw:Callable[[torch.Tensor],torch.Tensor],bw:Callable[[torch.Tensor],torch.Tensor], x:torch.Tensor)->torch.Tensor:
            return fw(x)
        
        @staticmethod
        def setup_context(ctx: Any, inputs: tuple[Callable[[torch.Tensor],torch.Tensor],Callable[[torch.Tensor],torch.Tensor],torch.Tensor], output: torch.Tensor) ->torch.Tensor:
            ctx.fw, ctx.bw, x = inputs
            return output
            
        @staticmethod
        def backward(ctx, grad_output:torch.Tensor):
            return None,None,_AutogradWrapper.apply(ctx.bw,ctx.fw,grad_output)

class LinearOperator(torch.nn.Module):
    """A Linear Operator with forward and adjoint methods."""
    def forward(self, x:torch.Tensor)->tuple[torch.Tensor]:
        """Apply to Operator to x."""  
        return (_AutogradWrapper.apply(self._forward_implementation,self._adjoint_implementation,x),)
    def adjoint(self,x:torch.Tensor)->tuple[torch.Tensor]:
        """Apply the adjoint of the Operator to x.""" 
        return  (_AutogradWrapper.apply(self._adjoint_implementation,self._forward_implementation,x),)
           
        
class TestOp(LinearOperator):
    """A simple multiplication."""
    def __init__(self,factor:float):
        super().__init__()
        self.factor = factor
    
    def _forward_implementation(self,x:torch.Tensor)->torch.Tensor:
        return x*self.factor
    
    def _adjoint_implementation(self,x:torch.Tensor)->torch.Tensor:
        return x*self.factor
```

So, we need 
- a Wrapper  for autograd.Function.
- Change all linear operators NOT to have their own `adjoint` and `forward`, but instead an hidden adjoint_implementation and forward_implementation (tensor->tensor)
- In the LinearOperator Base class, implement forward and adjoint as wrapping the implementaitons with the autograd wrapper

**Comment by fzimmermann89** [comment]
@ckolbPTB Alternative:

```python

class _AutogradWrapper(torch.autograd.Function):
    """Wrap forward and adjoint functions for autograd."""

    # If the forward and adjoint implementation are vmap-compatible,
    # the function can be marked as such to enable vmap support.
    generate_vmap_rule = True

    @staticmethod
    def forward(  # type: ignore [override]
        fw: Callable[[torch.Tensor], tuple[torch.Tensor,]],
        bw: Callable[[torch.Tensor], tuple[torch.Tensor,]],  # noqa: ARG004
        x: torch.Tensor,
    ) -> tuple[torch.Tensor,]:
        return fw(x)

    @staticmethod
    def setup_context(
        ctx: Any,  # noqa: ANN401
        inputs: tuple[Callable[[torch.Tensor], tuple[torch.Tensor,]], Callable[[torch.Tensor], tuple[torch.Tensor,]], torch.Tensor],
        output: tuple[torch.Tensor,],
    ) -> tuple[torch.Tensor,]:
        ctx.fw, ctx.bw, x = inputs
        return output

    @staticmethod
    def backward(ctx: Any, *grad_output: torch.Tensor) -> tuple[None, None, tuple[torch.Tensor,]]:  # noqa: ANN401
        return None, None, _AutogradWrapper.apply(ctx.bw, ctx.fw, grad_output[0])

    @staticmethod
    def jvp(ctx: Any, *grad_inputs: Any) -> tuple[torch.Tensor,]:  # noqa: ANN401
        return _AutogradWrapper.apply(ctx.fw, ctx.bw, grad_inputs[-1])


class LinearOperator(torch.nn.Module,ABC):
    """General Linear Operator."""
    
    def adjoint_wrapper(self, x: torch.Tensor) -> tuple[torch.Tensor,]:
        """Wraps the adjoint"""
        return (_AutogradWrapper.apply(lambda x:self._adjoint_implementation, self._adjoint_implementation, x),)
        

    def forward_wrapper(self, x: torch.Tensor) -> tuple[torch.Tensor]:
        """Wraps the forward"""
        return (_AutogradWrapper.apply(self._forward_implementation, self._adjoint_implementation, x),)

    def __init_subclass__(cls, **kwargs: Any) -> None:
       """ Wrap the forward and adjoint functions for autugrad"""
        cls._forward_implementation = cls.forward
        cls._adjoint_implementation = cls.adjoint
        cls.forward = LinearOperator.forward_wrapper
        cls.adjoint = LinearOperator.adjoint_wrapper
        super().__init_subclass__(**kwargs)
        
    @abstractmethod
    def forward(x):...    
    
    @abstractmethod
    def adjoint(x):...
    
    

class Test(LinearOperator):
    def forward(self, x: torch.Tensor) -> tuple[torch.Tensor,]:        
        "docstring"
        return x
    def adjoint(self, x: torch.Tensor) -> tuple[torch.Tensor,]:
        "docstring"
        return x


``` 

This would keep the forward and adjoint docstrings on Test.forward and adjoint, and would not require any changes to the actual operators. Not sure which way is easier to understand and continue to work with.

**Comment by ckolbPTB** [comment]
made a start here 

https://github.com/PTB-MR/mrpro/blob/autograd_wrapper_lin_op/src/mrpro/operators/LinearOperator.py

but not working yet

**Comment by fzimmermann89** [comment]
Re #307 #306

**Comment by fzimmermann89** [comment]
The __init_subclass__ approach mighht have issues with, for example, LinearOperatorSum etc, which inherit the forward from another Operator and only implement the adjoiunt

**Comment by ckolbPTB** [comment]
Unfortunately removing the abstract forward-method from LinearOperator did not work but leads to:

src/mrpro/operators/LinearOperator.py:86: error: Incompatible types in assignment (expression has type "Callable[[Operator[*Tin, Tout], VarArg(*Tin)], Tout]", variable has type "Callable[[LinearOperator, Tensor], tuple[Tensor]]")  [assignment]
src/mrpro/operators/LinearOperator.py:86: note: Error code "assignment" not covered by "type: ignore" comment

where line 86 is: `cls._forward_implementation = cls.forward  # type: ignore [method-assign]`

**Comment by ckolbPTB** [comment]
With the abstract forward-method we get the following errors:
src/mrpro/operators/LinearOperator.py:226: error: Cannot instantiate abstract class "LinearOperatorComposition" with abstract attribute "forward"  [abstract]
src/mrpro/operators/LinearOperator.py:249: error: Cannot instantiate abstract class "LinearOperatorSum" with abstract attribute "forward"  [abstract]
src/mrpro/operators/LinearOperator.py:256: error: Cannot instantiate abstract class "LinearOperatorElementwiseProductLeft" with abstract attribute "forward"  [abstract]
src/mrpro/operators/LinearOperator.py:263: error: Cannot instantiate abstract class "LinearOperatorElementwiseProductRight" with abstract attribute "forward"  [abstract]

So one option could be to add the forward methods to these LinearOperators by calling the super().forward

**Comment by fzimmermann89** [comment]
> Unfortunately removing the abstract forward-method from LinearOperator did not work but leads to:
> 
> src/mrpro/operators/LinearOperator.py:86: error: Incompatible types in assignment (expression has type "Callable[[Operator[*Tin, Tout], VarArg(*Tin)], Tout]", variable has type "Callable[[LinearOperator, Tensor], tuple[Tensor]]") [assignment] src/mrpro/operators/LinearOperator.py:86: note: Error code "assignment" not covered by "type: ignore" comment
> 
> where line 86 is: `cls._forward_implementation = cls.forward # type: ignore [method-assign]`

This should be possible to either solve with an #ignore on the assignment, a type hint on the forward method or a cast...
