### ISSUE TITLE
Add expected dimension comments

### ISSUE THREAD

**Issue by fzimmermann89** [PTB-MR/mrpro#71]
_Originally posted by @schuenke in https://github.com/ckolbPTB/mrpro/pull/70#pullrequestreview-1650087452_ :
Maybe we can add some more infos about the (expected) dimensions. Not just for the new KTrajectory dataclass, but also for all the other data classes and methods/functions.

 
 So the task might be to add useful dimension comments:
 - to our docstrings
 - to the variables in dataclasses as a comment.
 - In our code whenever we do some reshaping/rearranging that is not completely self-documenting (I.e. an einops call with named axes is fine, a moveaxis or `x[..,None,:,None:]` could get a small comment in the spirit of 
 `'... kx ky ->... coils=1,kx, kz=1,ky'`

**Comment by fzimmermann89** [comment]
In the same stroke, we might replace some uses of
- `moveaxis` by `einops.rearrange`
- `data[None,:,None]` / `einops.rearrange(data, "(other new1) old new2 ... -> new1 old new2...", new1=1,new2=1)` (and similar)  by `einops.repeat(old ...->new1 old new2 ..., new1=1,new2=1)` 

to make the code self-documenting

**Comment by ckolbPTB** [comment]
related to #250 #138 #102 #71
