### ISSUE TITLE
Failing tests result in green checkmark

### ISSUE THREAD

**Issue by fzimmermann89** [PTB-MR/mrpro#73]
Not sure if feature or bug:

Failing pytest tests result in a green checkmark for the action.

At least for me, this was surprising, as it is different for the pre-commit hook checks.

Do we want to change it and have a red check mark if at least one test is failing?
Or do we want to leave the green checkmark to signify that the testing framework worked, even though we had test failures?

(Example https://github.com/ckolbPTB/mrpro/pull/70)

**Comment by ckolbPTB** [comment]
Failing pytest should not lead to a green check mark. The main point of these checks is to ensure that nobody can merge something into main which fails the tests.

**Comment by fzimmermann89** [comment]
This should now be fixed in #74 , I'd like to get Patricks opinion on the approach, there might be a better way that I did not find.
