### ISSUE TITLE
Discussion: Workflows should run on each commit to main

### ISSUE THREAD

**Issue by fzimmermann89** [PTB-MR/mrpro#80]
It would be nice to know, that our workflows (tests and lint) succeed for each commit to main.

This will in the future allow us to use `git bisect` if we notice a bug and want to know when it was introduced.
For this to work, each single commit into main should "work"
Or we should never use rebase&merge to put separate commits into main for different changesets, and instead use separate PRs.

I do not know how to ensure that the workflows run on each commit if force-pushing to a PR or if this is even possible at all  (as I could not find a solution by a quick google search).

**Comment by fzimmermann89** [comment]
Or, after rebasing one can push the commits one after the other force github to run the action on each of them.
Maybe somebody can come up with a bash-one-liner that does this?

**Comment by ckolbPTB** [comment]
If we always to merge-commits, each commit in each push to main will pass all tests. 

For any other pushes I don't see how this can be enforced. What if you make a mistake and only realise after committing and pushing to the PR that it is not working? then you would need to fix it and merge it with the fix-it-commit to get a commit which passes all tests. If you notice the error straight away it is doable but if you realise that out of your 10 commits, commit 2 and 7 don't pass the tests, then it gets quite complex.

**Comment by fzimmermann89** [comment]
So only allow squashed-merge for PRs?

And use ghsack to split multiple commits into different PRs.

(Main should disallow direct pushes anyway.)

**Comment by ckolbPTB** [comment]
close once we have confirmed that only squash-merge can be selected in a PR

**Comment by schuenke** [comment]
With the current settings this IS the case already, no ?!

![grafik](https://github.com/PTB-MR/mrpro/assets/37338697/7bb931f4-0887-41dc-bca2-d3d2fb512fc7)

![grafik](https://github.com/PTB-MR/mrpro/assets/37338697/b302488b-4395-4e56-82e8-3558bd7f71b0)
