### ISSUE TITLE
RPE acquisition model

### ISSUE THREAD

**Issue by ckolbPTB** [PTB-MR/mrpro#9]
Acquisition model for (Golden) Radial Phase Encoding

Check list:
- [x]     Create branch
- [ ]     Implement code
- [ ]     Add comments
- [ ]     Implement tests
- [ ]     Squash commmits
- [ ]     Create PR
- [ ]     Assign reviewer(s) to PR

**Comment by ckolbPTB** [comment]
https://github.com/ckolbPTB/mrpro/tree/rpe_acq_model

**Comment by fzimmermann89** [comment]
It could be nice to do something similar to https://github.com/ckolbPTB/mrpro/blob/15518d41a05515ed175b50f2a10703e6f2b65631/src/mrpro/data/_DcfData.py#L144-L160
and handle all the trajectories at once in a general FourierOperator

 - If there are broadcasted dimensions in the KTrajectroy, to the transform along the broadcasted dimension as a 1D transform.
      a) if the 1D dimension is uniform, do a FFT
      b) if the 1D dimension is non-unifirm, do a nufft
 - Do a nufft on the remaining dimensions.

**Comment by ckolbPTB** [comment]
Yes, that would be a very neat implementation. 

Does anybody now of any performance difference in pytorch regarding 2x fft1d vs 1x fft2d? For torchkbnufft - at least from my experience - the main time consuming parts are the interpolation (matrix multiplication so that should be fine) and again ffts.

**Comment by fzimmermann89** [comment]
Even better (Pseudocode):
```
FFT_dims:list[int]=[]
NUFFT_dims:list[list[int]]=[]
For dimension in trajectory_dimensions:
  if dimension is broadcasted and uniform: # A cartesian dimension
    FFT_dims+=dimension
  elif dimension is broadcasted  # A non-uniform, but separable dimensoin
     NUFFT_dims+=[dimension]
  else: # A full dimension
    NUFFT_dims[0]+=dimension

if FFT_dims:
    x=FFTn(x,dims=FFT_dims)
for dims in nufft_dims: 
    temp_traj=stack(trajectories for dims)
    reshaped_x = move_other_dims_to_batch(x,dims) # this logic is currently in smap, but can be moved to a separate function
    reshaped_x = nufft(reshaped_x, omega=temp_traj)
    x=move_dims_back(x,dims)
```

We call the FFT only once, the nufft with the optimal number of calls.

**Comment by ckolbPTB** [comment]
It would be great if we could also call NUFFT only once because then the coil combination is done efficiently within torchkbnufft and we do not have to keep x-k-coil images in memory.

**Comment by fzimmermann89** [comment]
Two Arguments
A) Torchkbnufft also just implements the sensitivities as a multiplication in python: https://github.com/mmuckley/torchkbnufft/blob/20c45a23b4d2894fd118904131129d51104cd64f/torchkbnufft/modules/kbnufft.py#L182 , similar for adjoint and toeplitz. 


So if tracking gradients, the intermediate tensors will be kept in memory. 
If not tracking gradients, it makes no difference if we let torchkbnufft do the multiplication or if we do
`k=A(C(x))`

So there is no efficiency gain. (I would even suggest to have the sensitivities as a separate operator)
Please correct me is I misread the torchkbnufft source code.

B)
For a true nufft case, with the pseudocode above, the nufft is only called once.
So for example, a 2D radial trajectory would result in a single call, as no dimension is broadcasted, and only   NUFFT_dims[0] contains dimensions.
For RPE, it would be called once, and the normal fft would be called once.
The nufft is only called twice for non-uniform, broadcasted dimensions.
For example (ignore that this makes no sense), a RPE with non-uniform frequency encoding would do one 2D nufft in z,y and one 1D nufft in x. And this will be more efficient compared to doing the interpolation in 3D.

**Comment by ckolbPTB** [comment]
> Torchkbnufft also just implements the sensitivities as a multiplication in python

Surprisingly true - I had thought that this is done on a much lower level to save on memory. Then I agree, there is not efficiency difference. 

> For example, a RPE with non-uniform frequency encoding would do one 2D nufft in z,y and one 1D nufft in x.
> And this will still be more efficient compared to doing the interpolation in 3D.

Ok, then I misread the pseudo-code above. This sounds fine to me then.

**Comment by ckolbPTB** [comment]
Close by PR #104
