### ISSUE TITLE
Framework for examples

### ISSUE THREAD

**Issue by ckolbPTB** [PTB-MR/mrpro#93]
Set up framework to 

- have example scripts (.py) which show application of mrpro on real data (e.g. downloaded from zenodo)
- automatically create example notebooks with results (e.g. reconstruction images) as github actions
- add these example notebooks to documentation (requires #92)

**Comment by schuenke** [comment]
This package might be suiteable for the conversion of scripts (.py) to notebooks (.ipynb):
https://github.com/remykarem/python2jupyter
