### ISSUE TITLE
Refactor CSM + DCF calculation functions into module?

### ISSUE THREAD

**Issue by fzimmermann89** [PTB-MR/mrpro#96]
I am wondering if we want to keep the CSM/DCF calculation as partof the CSMData / DCFData classes or if we should move them into an algorithm/... namespace and have only the read/write/store functionality in the mrpro.data-classes.

Currently, they are part of the *Data-Classes. But for the reconstruction, we plan to have a separate namespace (not an IData.from_KData_cg....) 
So KData/IData/QData are different in scope than the CSM/DCF classes.
I think I prefer the KData/IData/QData way and have most of the more complex algorithmic/math stuff not in the data classes.

(We could also go a hybrid way and have the logic as part of a different module, but have small convenience classmethods in DCF/CSM that just call the logic if think it might be too cumbersome to have `CSM=mrpro.csm_estimation.walsh(images)` in an reconstruction script.

**Comment by ckolbPTB** [comment]
Done when code was refactored.

**Comment by ckolbPTB** [comment]
Done for CSM but not for DCF. Suggestion:

move `_dcf_2d3d_voronoi(traj: torch.Tensor) -> torch.Tensor:`

https://github.com/PTB-MR/mrpro/blob/0730e0608366b422c59c0c5ffa50a94fba671cf2/src/mrpro/data/DcfData.py#L93C9-L93C26 

to algorithms/dcf

**Comment by ckolbPTB** [comment]
move also `_dcf_1d(traj: torch.Tensor) -> torch.Tensor:`

https://github.com/PTB-MR/mrpro/blob/630cd700691850bfbd64a9ddf949867383118e19/src/mrpro/data/DcfData.py#L53

to algorithms/dcf
