### ISSUE TITLE
move largest EW/EV estimation into function

### ISSUE THREAD

**Issue by fzimmermann89** [PTB-MR/mrpro#97]
We could move the estimation of the largest eigenwert and eigenvector by poweriteration into an `mrpro.algorithm`-function.
This function will be used toestimate the condition of Operators as well as in the espirit and walsh csm calculation.

The signature could maybe be  (pseudocode)
```
def poweriteration(operator:Callable[[torch.tensor],torch.tensor]|, v0:torch.tensor, norm:Callable[[torch.Tensor,torch.Tensor]]|Sequence[int], n_iterations:int=10)->tuple[torch.Tensor,torch.Tensor]:
   
   if isinstance(norm,Sequence):
       norm = lambda x: l2 norm along norm dimensions
   for i in range(n_iterations):
      ...
   return eigenvector, eigenvalue
```

**Comment by ckolbPTB** [comment]
operator norm added in #224 EW/EV calculation only a few lines of code when optimised for a specific problem. general form too much overhead
